/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.DriverLicence;
import model.Person;

/**
 *
 * @author jayas
 */
public class UpdateDriversLicenceJPanel extends javax.swing.JPanel {

    Person person;
    /**
     * Creates new form DriversLicenceJPanel
     */
    public UpdateDriversLicenceJPanel(Person person) {
        initComponents();
        this.person = person;
    }
    
    public ImageIcon resizeImage(String imagePath) {
        ImageIcon imageIcon = new ImageIcon(imagePath);
        Image image = imageIcon.getImage().getScaledInstance(20, 30, Image.SCALE_SMOOTH);
        return new ImageIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDriversLicence = new javax.swing.JLabel();
        lblLicenceNum = new javax.swing.JLabel();
        lblDateIssued = new javax.swing.JLabel();
        lblDateExpiry = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        txtLicenceNum = new javax.swing.JTextField();
        txtDateIssued = new javax.swing.JTextField();
        txtDateExpiry = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        btnDriversLicence = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();

        lblDriversLicence.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDriversLicence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDriversLicence.setText("Drivers Licence Details");

        lblLicenceNum.setText("Licence Number:");

        lblDateIssued.setText("Issued Date:");

        lblDateExpiry.setText("Date of Expiration:");

        lblBloodType.setText("Blood Type:");

        lblPicture.setText("Picture:");

        btnDriversLicence.setText("Update");
        btnDriversLicence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDriversLicenceActionPerformed(evt);
            }
        });

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDriversLicence, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPicture)
                    .addComponent(lblBloodType)
                    .addComponent(lblDateExpiry)
                    .addComponent(lblDateIssued)
                    .addComponent(lblLicenceNum))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtLicenceNum, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addComponent(txtDateIssued)
                        .addComponent(txtDateExpiry)
                        .addComponent(txtBloodType))
                    .addComponent(btnBrowse))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDriversLicence)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblDriversLicence)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenceNum)
                    .addComponent(txtLicenceNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateIssued)
                    .addComponent(txtDateIssued, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateExpiry)
                    .addComponent(txtDateExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodType)
                    .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPicture)
                    .addComponent(btnBrowse))
                .addGap(18, 18, 18)
                .addComponent(btnDriversLicence)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDriversLicenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriversLicenceActionPerformed
        // TODO add your handling code here:
        DriverLicence driverLicence = new DriverLicence();
        driverLicence.setBloodType(txtBloodType.getText());
        driverLicence.setDateExpiry(txtDateExpiry.getText());
        driverLicence.setDateIssued(txtDateIssued.getText());
        driverLicence.setLicNum(txtLicenceNum.getText());
        
        person.setDriverLicence(driverLicence);
        
        JOptionPane.showMessageDialog(this, "Drivers Licence Details Updated Successfully");
        
    }//GEN-LAST:event_btnDriversLicenceActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".Images", "jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            btnBrowse.setIcon(resizeImage(path));
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_btnBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnDriversLicence;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblDateExpiry;
    private javax.swing.JLabel lblDateIssued;
    private javax.swing.JLabel lblDriversLicence;
    private javax.swing.JLabel lblLicenceNum;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtDateExpiry;
    private javax.swing.JTextField txtDateIssued;
    private javax.swing.JTextField txtLicenceNum;
    // End of variables declaration//GEN-END:variables
}
