/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JSplitPane;

/**
 *
 * @author jayas
 */
public class UpdateDetailsJPanel extends javax.swing.JPanel {

    MainJFrame mainJFrame;
    /**
     * Creates new form UpdateDetailsJPanel
     */
    public UpdateDetailsJPanel(MainJFrame mainJFrame) {
        initComponents();
        this.mainJFrame = mainJFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDemographic = new javax.swing.JButton();
        btnUpdateBank = new javax.swing.JButton();
        btnUpdateDriversLicence = new javax.swing.JButton();
        btnUpdateMedRec = new javax.swing.JButton();
        btnUpdateAddress = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose what to be updated");

        btnDemographic.setText("Demographic Info");
        btnDemographic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDemographic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemographicActionPerformed(evt);
            }
        });

        btnUpdateBank.setText("Bank Details");
        btnUpdateBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBankActionPerformed(evt);
            }
        });

        btnUpdateDriversLicence.setText("Drivers Licence");
        btnUpdateDriversLicence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDriversLicenceActionPerformed(evt);
            }
        });

        btnUpdateMedRec.setText("Medical Records");
        btnUpdateMedRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMedRecActionPerformed(evt);
            }
        });

        btnUpdateAddress.setText("Address");
        btnUpdateAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdateBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateDriversLicence, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdateMedRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnDemographic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(btnDemographic)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateBank)
                    .addComponent(btnUpdateAddress))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdateDriversLicence)
                    .addComponent(btnUpdateMedRec))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDemographicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemographicActionPerformed
        // TODO add your handling code here:
        mainJFrame.getSplitPane().setRightComponent(new UpdatePersonJPanel(mainJFrame.getPerson()));
    }//GEN-LAST:event_btnDemographicActionPerformed

    private void btnUpdateBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBankActionPerformed
        // TODO add your handling code here:
        mainJFrame.getSplitPane().setRightComponent(new UpdateBankJPanel(mainJFrame.getPerson()));
    }//GEN-LAST:event_btnUpdateBankActionPerformed

    private void btnUpdateAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAddressActionPerformed
        // TODO add your handling code here:
        mainJFrame.getSplitPane().setRightComponent(new UpdateAddressJPanel(mainJFrame.getPerson()));
    }//GEN-LAST:event_btnUpdateAddressActionPerformed

    private void btnUpdateDriversLicenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDriversLicenceActionPerformed
        // TODO add your handling code here:
        mainJFrame.getSplitPane().setRightComponent(new UpdateDriversLicenceJPanel(mainJFrame.getPerson()));
    }//GEN-LAST:event_btnUpdateDriversLicenceActionPerformed

    private void btnUpdateMedRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMedRecActionPerformed
        // TODO add your handling code here:
        mainJFrame.getSplitPane().setRightComponent(new UpdateMedicalRecJPanel(mainJFrame.getPerson()));
    }//GEN-LAST:event_btnUpdateMedRecActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDemographic;
    private javax.swing.JButton btnUpdateAddress;
    private javax.swing.JButton btnUpdateBank;
    private javax.swing.JButton btnUpdateDriversLicence;
    private javax.swing.JButton btnUpdateMedRec;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
