/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Bank;
import model.Person;

/**
 *
 * @author jayas
 */
public class UpdateBankJPanel extends javax.swing.JPanel {

    Person person;
    /**
     * Creates new form BankJPanel
     */
    public UpdateBankJPanel(Person person) {
        initComponents();
        this.person = person;
        txtCheckingAccNum.setText(person.getCheckingAcc().getAccNum());
        txtCheckingBalance.setText(person.getCheckingAcc().getAccBal());
        txtCheckingBankName.setText(person.getCheckingAcc().getName());
        txtCheckingRoutingNum.setText(person.getCheckingAcc().getRoutingNum());
        txtSavingsAccNum.setText(person.getSavingsAcc().getAccNum());
        txtSavingsBalance.setText(person.getSavingsAcc().getAccBal());
        txtSavingsBankName.setText(person.getSavingsAcc().getName());
        txtSavingsRoutingNum.setText(person.getSavingsAcc().getRoutingNum());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBank = new javax.swing.JLabel();
        lblSavings = new javax.swing.JLabel();
        lblChecking = new javax.swing.JLabel();
        lblSavingsAccNum = new javax.swing.JLabel();
        lblSavingsBankName = new javax.swing.JLabel();
        lblSavingsRoutingNum = new javax.swing.JLabel();
        lblSavingsBalance = new javax.swing.JLabel();
        lblCheckingAccNum = new javax.swing.JLabel();
        lblCheckingBankName = new javax.swing.JLabel();
        lblCheckingRoutingNum = new javax.swing.JLabel();
        lblCheckingBalance = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtSavingsBankName = new javax.swing.JTextField();
        txtSavingsRoutingNum = new javax.swing.JTextField();
        txtSavingsAccNum = new javax.swing.JTextField();
        txtSavingsBalance = new javax.swing.JTextField();
        txtCheckingBankName = new javax.swing.JTextField();
        txtCheckingRoutingNum = new javax.swing.JTextField();
        txtCheckingAccNum = new javax.swing.JTextField();
        txtCheckingBalance = new javax.swing.JTextField();
        btnUpdateCheckingBank = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnUpdateSavingsBank = new javax.swing.JButton();

        lblBank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBank.setText("Bank Details");

        lblSavings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSavings.setText("Savings");

        lblChecking.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChecking.setText("Checking");

        lblSavingsAccNum.setText("Account Number:");

        lblSavingsBankName.setText("Bank Name:");

        lblSavingsRoutingNum.setText("Routing Number:");

        lblSavingsBalance.setText("Balance:");

        lblCheckingAccNum.setText("Account Number:");

        lblCheckingBankName.setText("Bank Name:");

        lblCheckingRoutingNum.setText("Routing Number:");

        lblCheckingBalance.setText("Balance:");

        txtCheckingBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckingBankNameActionPerformed(evt);
            }
        });

        btnUpdateCheckingBank.setText("Update");
        btnUpdateCheckingBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCheckingBankActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnUpdateSavingsBank.setText("Update");
        btnUpdateSavingsBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSavingsBankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSavingsBankName)
                            .addComponent(lblSavingsAccNum)
                            .addComponent(lblSavingsRoutingNum)
                            .addComponent(lblSavingsBalance))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSavingsAccNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(txtSavingsRoutingNum, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSavingsBankName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSavingsBalance))
                            .addComponent(lblSavings))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpdateSavingsBank)
                        .addGap(47, 47, 47)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCheckingAccNum)
                                .addComponent(lblCheckingRoutingNum)
                                .addComponent(lblCheckingBalance))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblCheckingBankName)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCheckingBankName, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txtCheckingRoutingNum)
                            .addComponent(txtCheckingAccNum)
                            .addComponent(txtCheckingBalance))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblChecking)
                                .addGap(126, 126, 126))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnUpdateCheckingBank)
                                .addGap(39, 39, 39))))))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblBank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSavings)
                            .addComponent(lblChecking))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblCheckingBankName)
                                            .addComponent(txtCheckingBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblCheckingRoutingNum)
                                            .addComponent(txtCheckingRoutingNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblCheckingAccNum)
                                            .addComponent(txtCheckingAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblCheckingBalance)
                                            .addComponent(txtCheckingBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblSavingsBankName)
                                            .addComponent(txtSavingsBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblSavingsRoutingNum)
                                            .addComponent(txtSavingsRoutingNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblSavingsAccNum)
                                            .addComponent(txtSavingsAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblSavingsBalance)
                                            .addComponent(txtSavingsBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(btnUpdateCheckingBank)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateSavingsBank)
                                .addGap(21, 21, 21))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCheckingBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckingBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckingBankNameActionPerformed

    private void btnUpdateSavingsBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSavingsBankActionPerformed
        // TODO add your handling code here:
        Bank bank = new Bank();
        bank.setAccBal(txtSavingsBalance.getText());
        bank.setAccNum(txtSavingsAccNum.getText());
        bank.setAccType("Savings");
        bank.setName(txtSavingsBankName.getText());
        bank.setRoutingNum(txtSavingsRoutingNum.getText());
        
        person.setSavingsAcc(bank);
        
        JOptionPane.showMessageDialog(this, "Savings Account Details Updated Successfully");
        
    }//GEN-LAST:event_btnUpdateSavingsBankActionPerformed

    private void btnUpdateCheckingBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCheckingBankActionPerformed
        // TODO add your handling code here:
        Bank bank = new Bank();
        bank.setAccBal(txtCheckingBalance.getText());
        bank.setAccNum(txtCheckingAccNum.getText());
        bank.setAccType("Checking");
        bank.setName(txtCheckingBankName.getText());
        bank.setRoutingNum(txtCheckingRoutingNum.getText());
        
        person.setCheckingAcc(bank);
        
        JOptionPane.showMessageDialog(this, "Checking Account Details Updated Successfully");
        
    }//GEN-LAST:event_btnUpdateCheckingBankActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateCheckingBank;
    private javax.swing.JButton btnUpdateSavingsBank;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblChecking;
    private javax.swing.JLabel lblCheckingAccNum;
    private javax.swing.JLabel lblCheckingBalance;
    private javax.swing.JLabel lblCheckingBankName;
    private javax.swing.JLabel lblCheckingRoutingNum;
    private javax.swing.JLabel lblSavings;
    private javax.swing.JLabel lblSavingsAccNum;
    private javax.swing.JLabel lblSavingsBalance;
    private javax.swing.JLabel lblSavingsBankName;
    private javax.swing.JLabel lblSavingsRoutingNum;
    private javax.swing.JTextField txtCheckingAccNum;
    private javax.swing.JTextField txtCheckingBalance;
    private javax.swing.JTextField txtCheckingBankName;
    private javax.swing.JTextField txtCheckingRoutingNum;
    private javax.swing.JTextField txtSavingsAccNum;
    private javax.swing.JTextField txtSavingsBalance;
    private javax.swing.JTextField txtSavingsBankName;
    private javax.swing.JTextField txtSavingsRoutingNum;
    // End of variables declaration//GEN-END:variables
}
